spring:
  profiles:
    active: dev
  application:
    name: macboss-api
    
  # Conexão com o PostgreSQL do Docker
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:macboss_db}
    username: ${DB_USER:macboss_user}
    password: ${DB_PASS:macboss_admin123}
    
  # Configuração do JPA (Mapeamento Objeto-Relacional)
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
  # Conexão com o Redis do Docker
  data:
    redis:
      host: localhost
      port: 6379
      
  # Controle de versão do Banco de Dados
  flyway:
    enabled: true
    baseline-on-migrate: true

# Regra de Segurança da nossa Auditoria (Apenas Health Check visível)
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
jwt:
  secret: ${JWT_SECRET:CHAVE_DE_DESENVOLVIMENTO_GIGANTE_E_SEGURA_DO_MACBOSS_MINIMO_256_BITS}
  expiration: 900000 # 15 minutos (Access Token)
  refresh-expiration: 604800000 # 7 dias (Refresh Token)

admin:
  default:
    email: ${ADMIN_DEFAULT_EMAIL:admin@macboss.com}
    password: ${ADMIN_DEFAULT_PASSWORD:admin123}
